// Source of truth for the weekend. `loc` is [lat, lon] for the map,
// `place` is what gets sent to the maps app for directions.
const BEAULIEU = [50.818, -1.452];

export const trip = {
  title: "Dad's 70th",
  subtitle: 'Beaulieu, New Forest',
  start: { name: 'Hampstead', loc: [51.556, -0.178] },
  base: { name: 'Beaulieu', loc: BEAULIEU },
  days: [
    {
      id: 'sat',
      label: 'Saturday',
      date: '2026-09-05',
      note: 'Drive down. Vikings at midday, then feet up.',
      from: 'start',
      to: 'base',
      slots: [
        {
          id: 'sat-am',
          title: 'The stop on the way down',
          pick: 'Leaving Hampstead by 10 puts you at Butser for midday, and at the hotel by four.',
          options: [
            {
              id: 'butser',
              name: 'Butser Ancient Farm',
              meta: '1h45 down the A3, 1½ to 2 hrs there, then 1h on to Beaulieu',
              why: 'A reconstructed ancient settlement in the South Downs: Iron Age roundhouses, a Roman villa and a great Anglo-Saxon hall, with fires burning inside and people showing how life was lived. Today is their Viking weekend, with costumed villagers and warriors, weapons displays and living history, 10am to 4pm.',
              access: 'Five acres, mostly flat, bonded-gravel paths. Nearly every building takes a wheelchair and they lend them free. Benches everywhere, and he can sit inside by the fire.',
              cost: '£15.50 adult, £14.50 concession, less online',
              cover: 'Both',
              event: 'Viking weekend today, 10am to 4pm',
              loc: [50.9598, -0.977],
              place: 'Butser Ancient Farm, Chalton, Waterlooville',
              best: true,
            },
            {
              id: 'weald',
              name: 'Weald & Downland Living Museum',
              meta: '2h there, near Chichester, then 1h30 on to Beaulieu',
              why: 'Fifty rescued historic buildings rebuilt across a rural landscape. Threshing weekend today with working horses and demonstrations. The bigger version of Butser.',
              access: 'Forty acres with slopes, gravel and uneven ground. Too much walking for him, honestly.',
              cost: 'About £17',
              cover: 'Both',
              event: 'Threshing weekend today',
              loc: [50.909, -0.755],
              place: 'Weald & Downland Living Museum, Singleton',
            },
            {
              id: 'salisbury',
              name: 'Salisbury Cathedral',
              meta: '90 min there, adds about 40 min driving',
              why: "Tallest spire in Britain, a 1215 Magna Carta in the Chapter House, and the world's oldest working clock from about 1386.",
              access: 'Level throughout. Wheelchairs available, seating everywhere.',
              cost: 'Donation, around £10 suggested',
              cover: 'Indoors',
              loc: [51.065, -1.797],
              place: 'Salisbury Cathedral',
            },
            {
              id: 'romsey',
              name: 'Romsey Abbey',
              meta: '40 min there, directly on the M27',
              why: 'One of the finest Norman churches in the country, and the Saxon rood outside is over a thousand years old.',
              access: 'Flat, small, no queues. Park almost outside.',
              cost: 'Free',
              cover: 'Indoors',
              loc: [50.989, -1.497],
              place: 'Romsey Abbey',
            },
            {
              id: 'sarum',
              name: 'Old Sarum',
              meta: '75 min there, next to Salisbury',
              why: 'Iron Age hillfort, Norman castle and the footprint of the original cathedral, all on one great mound.',
              access: 'Exposed, uneven, uphill. Only if he is having a good day.',
              cost: 'About £8, English Heritage',
              cover: 'Outdoors',
              loc: [51.093, -1.805],
              place: 'Old Sarum, Salisbury',
            },
            {
              id: 'straight',
              name: 'Straight to the hotel',
              meta: '2h15, no detour',
              why: 'Arrive early, long lunch, and let the whole afternoon go slowly. No shame in it.',
              access: 'Nothing required.',
              cost: 'Free',
              cover: 'Either',
              loc: BEAULIEU,
              place: 'Beaulieu, Brockenhurst',
            },
          ],
        },
        {
          id: 'sat-lunch',
          title: 'Lunch',
          pick: 'Late is fine. You are not on a schedule.',
          options: [
            {
              id: 'chalton',
              name: 'The Red Lion, Chalton',
              meta: '3 min from Butser',
              why: 'Thatched, timbered, and said to be the oldest pub in Hampshire, which is exactly the right lunch after a morning with the Vikings. Butser also has a small café if you would rather not move.',
              access: 'Flat, park outside. Low beams inside.',
              cost: '££',
              cover: 'Indoors',
              loc: [50.9605, -0.969],
              place: 'The Red Lion, Chalton, Waterlooville',
              best: true,
            },
            {
              id: 'sal-lunch',
              name: 'Salisbury, Cathedral Close',
              meta: 'After the cathedral',
              why: 'The Close is the prettiest part of the city and the walk from the cathedral door is short and flat.',
              access: 'Flat.',
              cost: '££',
              cover: 'Indoors',
              loc: [51.064, -1.797],
              place: 'Cathedral Close, Salisbury',
            },
            {
              id: 'hotel-lunch',
              name: 'At the hotel',
              meta: 'On arrival',
              why: 'Check in, drop the bags, eat where you are standing. Least effort of anything on this list.',
              access: 'None.',
              cost: '££',
              cover: 'Indoors',
              loc: BEAULIEU,
            },
            {
              id: 'pub-lunch',
              name: 'A Beaulieu village pub',
              meta: 'Walkable from the hotel',
              why: 'Village setting, river at the bottom of the road, and he gets a proper first pint of the weekend.',
              access: 'Short flat walk.',
              cost: '££',
              cover: 'Indoors',
              loc: [50.8175, -1.4525],
              place: 'Beaulieu village, Brockenhurst',
            },
          ],
        },
        {
          id: 'sat-pm',
          title: 'Afternoon',
          pick: 'Hotel around four. Optional after that. Skip the lot if the drive was enough.',
          options: [
            {
              id: 'settle',
              name: 'Settle in and do nothing',
              meta: 'Hotel lounge, or the pool',
              why: 'Fire, papers, a drink, a swim if he fancies it. This is what he said he wanted.',
              access: 'None.',
              cost: 'Free',
              cover: 'Indoors',
              loc: BEAULIEU,
              best: true,
            },
            {
              id: 'riverwalk',
              name: 'Beaulieu Mill Dam and river',
              meta: '10 min stroll',
              why: 'The millpond and the view back to the village is the postcard shot. Benches along it.',
              access: 'Flat, short, easy to turn back.',
              cost: 'Free',
              cover: 'Outdoors',
              loc: [50.8185, -1.455],
              place: 'Beaulieu Mill Dam',
            },
            {
              id: 'heath',
              name: 'Ponies on the heath from the car',
              meta: '20 min loop, Beaulieu Heath',
              why: 'The road out past Hatchet Pond has ponies and cattle wandering across it most evenings. Windows down, no walking.',
              access: 'Entirely from the car.',
              cost: 'Free',
              cover: 'Either',
              loc: [50.806, -1.507],
              place: 'Hatchet Pond, Beaulieu',
            },
            {
              id: 'exbury',
              name: 'Exbury Gardens',
              meta: '15 min drive',
              why: 'Rothschild estate gardens with a steam railway that does a 20-minute loop, so he sees it all sitting down.',
              access: 'Train removes the walking. Check last departure.',
              cost: '£££',
              cover: 'Outdoors',
              loc: [50.799, -1.398],
              place: 'Exbury Gardens',
            },
          ],
        },
        {
          id: 'sat-dinner',
          title: 'Birthday dinner',
          pick: 'Book it the moment you check in, not at 7pm.',
          options: [
            {
              id: 'montagu',
              name: "Monty's at the Montagu Arms, Beaulieu",
              meta: 'In the village',
              why: 'The old coaching inn at the top of the village: oak, open fires, real ale, proper food. The atmospheric pub you asked for, and only a stroll or a two-minute drive from anywhere in Beaulieu.',
              access: 'Level from the street, a few steps inside. Ask for a table by the fire.',
              cost: '£££',
              cover: 'Indoors',
              loc: [50.8188, -1.4508],
              place: "The Montagu Arms Hotel, Beaulieu",
              best: true,
            },
            {
              id: 'masterbuilders',
              name: "The Master Builder's, Buckler's Hard",
              meta: '6 min drive',
              why: 'Riverside inn on the old shipbuilding street. Worth it if you want one evening out by the water.',
              access: 'Flat, park close.',
              cost: '£££',
              cover: 'Indoors',
              loc: [50.8, -1.421],
              place: "The Master Builder's House Hotel, Buckler's Hard",
            },
            {
              id: 'hotel-dinner',
              name: 'The hotel restaurant',
              meta: 'No driving',
              why: 'Nobody drives, nobody rushes, and he goes upstairs afterwards.',
              access: 'None.',
              cost: '£££',
              cover: 'Indoors',
              loc: BEAULIEU,
            },
            {
              id: 'pig',
              name: 'The Pig, Brockenhurst',
              meta: '15 min drive',
              why: 'Kitchen-garden cooking in a forest house. Very good, books up fast, ring today.',
              access: 'Gravel drive, otherwise level.',
              cost: '£££',
              cover: 'Indoors',
              loc: [50.807, -1.55],
              place: 'The Pig, Brockenhurst',
            },
          ],
        },
      ],
    },
    {
      id: 'sun',
      label: 'Sunday',
      date: '2026-09-06',
      note: 'The abbey day. Most of it can be done from the car.',
      from: 'base',
      to: 'base',
      slots: [
        {
          id: 'sun-am',
          title: 'Morning',
          pick: 'Beaulieu is on your doorstep and the ticket lasts all day.',
          options: [
            {
              id: 'beaulieu',
              name: 'Beaulieu Abbey and Palace House',
              meta: 'Walk from the hotel, 2 to 3 hrs',
              why: 'Cistercian abbey founded by King John in 1204, the monks’ refectory now the parish church, Palace House built into the gatehouse, and the National Motor Museum with the veteran cars, all on one ticket.',
              access: 'Monorail and veteran bus on site cut out most of the walking.',
              cost: '££ one ticket, all day',
              cover: 'Both',
              loc: [50.8215, -1.451],
              place: 'Beaulieu National Motor Museum',
              best: true,
            },
            {
              id: 'bucklers',
              name: "Buckler's Hard",
              meta: '6 min drive, 1 to 2 hrs',
              why: "Georgian shipbuilding village where Nelson's ships were built. One short street, museum, cafe at the end.",
              access: 'One flat street. Genuinely easy.',
              cost: '££',
              cover: 'Both',
              loc: [50.8, -1.421],
              place: "Buckler's Hard",
            },
            {
              id: 'cruise',
              name: 'Beaulieu River cruise',
              meta: "30 min, from Buckler's Hard",
              why: 'Best views of the estuary and he never leaves his seat. Weather dependent, so ring ahead.',
              access: 'Step down into the boat. Ask about assistance.',
              cost: '£',
              cover: 'Outdoors',
              loc: [50.799, -1.42],
              place: "Buckler's Hard",
            },
          ],
        },
        {
          id: 'sun-lunch',
          title: 'Lunch',
          pick: '',
          options: [
            {
              id: 'lymington',
              name: 'Lymington',
              meta: '15 min drive',
              why: 'Georgian quay town, cobbled street down to the water, plenty of places to eat and watch boats.',
              access: 'The quay street is cobbled and slopes. Park at the top.',
              cost: '££',
              cover: 'Indoors',
              loc: [50.758, -1.541],
              place: 'Lymington Quay',
            },
            {
              id: 'mb-lunch',
              name: "The Master Builder's",
              meta: '6 min drive',
              why: "If you are already at Buckler's Hard, you are already there.",
              access: 'Flat.',
              cost: '££',
              cover: 'Indoors',
              loc: [50.8, -1.421],
              place: "The Master Builder's House Hotel, Buckler's Hard",
            },
            {
              id: 'burley',
              name: 'Burley village',
              meta: '25 min drive',
              why: "Thatched cottages, ponies wandering through, tea rooms and the Queen's Head. Very picture-book.",
              access: 'Small and flat.',
              cost: '££',
              cover: 'Indoors',
              loc: [50.827, -1.7],
              place: 'Burley, Ringwood',
            },
          ],
        },
        {
          id: 'sun-pm',
          title: 'The pony and forest run',
          pick: 'All of this works from the car if it rains.',
          options: [
            {
              id: 'rhinefield',
              name: 'Rhinefield Ornamental Drive',
              meta: 'Scenic drive, 30 min',
              why: 'Giant redwoods and Douglas firs planted in 1859, lining the road. Ponies on the tarmac throughout.',
              access: 'Entirely from the car. Pull-ins along the way.',
              cost: 'Parking only',
              cover: 'Either',
              loc: [50.825, -1.62],
              place: 'Rhinefield Ornamental Drive',
              best: true,
            },
            {
              id: 'bolderwood',
              name: 'Bolderwood Deer Sanctuary',
              meta: 'Short flat walk',
              why: 'Viewing platform overlooking a meadow where the fallow deer come out. Best late afternoon.',
              access: 'Level gravel path, a few hundred yards.',
              cost: 'Parking only',
              cover: 'Outdoors',
              loc: [50.876, -1.68],
              place: 'Bolderwood Deer Sanctuary',
            },
            {
              id: 'brock',
              name: 'Brockenhurst village and the ford',
              meta: 'Tea or a pint',
              why: 'Ponies and cattle wander the actual streets, and there is a water splash in the middle of the village.',
              access: 'Flat. Park and watch.',
              cost: 'Free',
              cover: 'Either',
              loc: [50.818, -1.574],
              place: 'Brockenhurst',
            },
            {
              id: 'lyndhurst',
              name: 'New Forest Centre, Lyndhurst',
              meta: 'Indoors, 1 hr',
              why: "The forest's story from William the Conqueror onwards. The rain plan that is not the hotel bar.",
              access: 'Level, small museum.',
              cost: '£',
              cover: 'Indoors',
              loc: [50.873, -1.577],
              place: 'New Forest Heritage Centre, Lyndhurst',
            },
          ],
        },
      ],
    },
    {
      id: 'mon',
      label: 'Monday',
      date: '2026-09-07',
      note: 'One last stop on the road home. Check out around 10:30.',
      from: 'base',
      to: 'start',
      slots: [
        {
          id: 'mon-am',
          title: 'On the way back',
          pick: 'Winchester costs you almost no extra driving. You are on the M3 anyway.',
          options: [
            {
              id: 'winchester',
              name: 'Winchester',
              meta: '40 min, 2 to 3 hrs there',
              why: 'Anglo-Saxon and Norman capital of England. Cathedral with the longest nave in Europe, Norman crypt, and the Round Table in the Great Hall five minutes away.',
              access: 'Flat, indoors, benches throughout. The best bad-weather option of the weekend.',
              cost: '££',
              cover: 'Indoors',
              loc: [51.061, -1.313],
              place: 'Winchester Cathedral',
              best: true,
            },
            {
              id: 'christchurch',
              name: 'Christchurch Priory',
              meta: '30 min, wrong direction',
              why: 'Superb Norman priory and castle ruins by the quay. Lovely, but it sends you west before you turn for home.',
              access: 'Flat.',
              cost: 'Donation',
              cover: 'Indoors',
              loc: [50.733, -1.775],
              place: 'Christchurch Priory',
            },
            {
              id: 'rufus',
              name: 'The Rufus Stone',
              meta: '20 min, roadside',
              why: 'Where William II took an arrow in 1100. Five minutes, one stone, a good story to tell in the car.',
              access: 'Short walk from the layby.',
              cost: 'Free',
              cover: 'Outdoors',
              loc: [50.925, -1.634],
              place: 'Rufus Stone, Lyndhurst',
            },
            {
              id: 'home',
              name: 'Straight home',
              meta: '2h15',
              why: 'Beat the traffic, end on a high, do not push it on the last day.',
              access: 'None.',
              cost: 'Free',
              cover: 'Either',
              loc: [51.556, -0.178],
              place: 'Hampstead, London',
            },
          ],
        },
        {
          id: 'mon-lunch',
          title: 'Last lunch',
          pick: '',
          options: [
            {
              id: 'wykeham',
              name: 'The Wykeham Arms, Winchester',
              meta: 'By the cathedral',
              why: 'Eighteenth-century pub tucked behind the Close, fires, old school desks for tables. A proper last stop.',
              access: 'Short flat walk from the cathedral.',
              cost: '££',
              cover: 'Indoors',
              loc: [51.0605, -1.3165],
              place: 'The Wykeham Arms, Winchester',
            },
            {
              id: 'refectory',
              name: 'Cathedral refectory',
              meta: 'On site',
              why: 'Zero extra walking, right by the cloister. The easy option.',
              access: 'None.',
              cost: '£',
              cover: 'Indoors',
              loc: [51.061, -1.313],
              place: 'Winchester Cathedral Refectory',
            },
            {
              id: 'roadside',
              name: 'Eat on the road',
              meta: 'M3',
              why: 'If he is tired, get him home. Nobody remembers the last lunch.',
              access: 'None.',
              cost: '£',
              cover: 'Indoors',
            },
          ],
        },
      ],
    },
  ],
};

export const totalSlots = trip.days.reduce((n, d) => n + d.slots.length, 0);
